[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#767676"
blue = "#1a8fff"
cyan = "#14ffff"
green = "#23fd00"
magenta = "#fd28ff"
red = "#f2201f"
white = "#ffffff"
yellow = "#fffd00"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#000000"
blue = "#0d73cc"
cyan = "#0dcdcd"
green = "#19cb00"
magenta = "#cb1ed1"
red = "#cc0403"
white = "#dddddd"
yellow = "#cecb00"

[colors.primary]
background = "#000000"
foreground = "#dddddd"

[colors.selection]
cursor = "#ffffff"
text = "CellForeground"

[cursor]
thickness = 0.15
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
# TERM = "alacritty"

[font]
size = 15.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Shift|Super"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/opt/homebrew/bin//fish"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 0.8
option_as_alt = "Both"
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 0
y = 0
